### ISSUE TITLE
Write only transactions are not atomic 

### ISSUE THREAD

**Issue by nike61** [Hangfire-Mongo/Hangfire.Mongo#320]
Hi,
Write only transactions uses bulk write which is not atomic in MongoDB. 

How do you think is it ok or maybe it’s better to consider using MongoDB sessions and multi-document transactions? 

I’m studying guarantees that this library provides before using it on production and I a bit worry that there are some scenarios that may lead to corrupted data or undefined behaviour.

**Comment by gottscj** [comment]
Hi @nike61,

Thank you for your feedback! 
I did write an implementation using transactions. but it didn't work due to the way Hangfire schedules changes, which can be conflicting on the same document which mongodb transactions doesnt support.
However All write operations use a unique key which ensures atomic operation on document level and all job data is in the same collection. Hangfire itself also wraps the entire write-operation in a distributed lock for that specific operation which also should ensure atomicity.
you can enable trace logging and review the filters/updates/inserts also which will give more insight into what is written in different scenarios.
I personally use this lib in multiple production environments without issue and I know others do successfully also. check out: 
https://github.com/Hangfire-Mongo/Hangfire.Mongo/issues/314#issuecomment-1175687446

However, this is a lib which is maintained in my spare time so there are no guarantees. :)
You override almost any behavior in the lib by inheriting the original. You also need to override the MongoFactory to return the correct instance. I would love to see a go with mongodb sessions!
I hope this answers your questions/concerns :)
